name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: '❗️ Breaking Changes'
    labels:
      - 'breaking'
  - title: '🛠 Maintenance'
    labels:
      - 'maintenance'
  - title: '📖 Documentation'
    labels:
      - 'docs'
change-template: '- $TITLE @$AUTHOR'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed
  $CHANGES
  
  ## Contributors
  Thanks to all our contributors! 🎉
autolabeler:
  - label: 'docs'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feat'
    branch:
      - '/feat\/.+/'