unique_ids:
  assets:
    standard-page.html: C6HVJ5UJ7MSZTKIGCLEGRZGX66GXSQBE
    theme.css: NEHP267FFS4D3BSA3GM5OARL2BNC7JM5
  forms: {}
  modules:
    startup: TDG2WASDMO4QJE3HAR6TGTQ2EQF5TQMP
  scripts:
    fix_version: 2ZIGV2HRCXIMLOYPH2LN6LL3GX2MILNS
  server_modules: {}
